#!/bin/sh
#SBATCH -q batch
#SBATCH -t 01:00:00
#SBATCH -N 8  
#SBATCH --ntasks-per-node=96
#SBATCH -J C96_3dvar_iau
#SBATCH -e C96_3dvar_iau.err
#SBATCH -o C96_3dvar_iau.out

export NODES=$SLURM_JOB_NUM_NODES
export corespernode=$SLURM_CPUS_ON_NODE
export machine='noaacloud'

# for control forecast
if [ $NODES -eq 8 ]; then
  # 8 nodes, 1 threads
  export control_threads=1
  export control_proc=768
  export write_groups_ctl=4 # write groups for control forecast.
  export write_tasks_ctl=24
  export layout_ctl="12,12" # layout_x,layout_y (total # mpi tasks = $layout_x*$layout_y*6=($fg_proc/$fg_threads) - $write_tasks*$write_groups)
else
  echo "processor layout for $NODES nodes not set"
  exit 1
fi

export fg_proc=$corespernode
export fg_threads=1 
export gsi_control_threads=8
